# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest:
  - resource: http://192.168.169.41:334/dw?area=temperature
    sensor:
      - name: "Raum"
        value_template: "{{ value_json[0]['value'][0]['temperature'] }}"  
        device_class: temperature
        unit_of_measurement: "°C"
        unique_id: "heizung.temp_luft"
      - name: "Boiler"
        value_template: "{{ value_json[0]['value'][1]['temperature'] }}"  
        device_class: temperature
        unit_of_measurement: "°C"
        unique_id: "heizung.temp_boiler"
      - name: "CO₂"
        value_template: "{{ value_json[0]['value'][2]['temperature'] }}"  
        device_class: carbon_dioxide
        unit_of_measurement: "ppm"
        unique_id: "heizung.co2"
  - resource: http://192.168.169.41:334/dw?area=values
    binary_sensor:
      - name: "Anforderung: Raum-Heizstufe 1"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 1032) | list | first).currentValue }}"
        unique_id: "heizung.anforderung_heizstufe_1"
        device_class: heat
      - name: "Anforderung: Raum-Heizstufe 2"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 1034) | list | first).currentValue }}"  
        unique_id: "heizung.anforderung2"
        device_class: heat
      - name: "Anforderung: Brauchwasserheizung Wärmepumpe"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 1036) | list | first).currentValue }}"  
        unique_id: "heizung.anforderung_brauchwasse_waermepumpe"
        device_class: running
      - name: " Anforderung: Brauchwasserheizung Elektroheizstab "
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 1038) | list | first).currentValue }}"      
        unique_id: "heizung.anforderung_brauchwasser_elektro"
        device_class: running
    sensor:  
      - name: "Verdampferregister"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 210) | list | first).currentValue / 1000 | round }}"
        unique_id: "heizung.temp_verdampfer"
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "Warmwasserspeicher oben"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 212) | list | first).currentValue / 1000 | round }}"
        unique_id: "heizung.temp_ww_oben"
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "Warmwasserspeicher WP"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 214) | list | first).currentValue / 1000 | round }}"
        unique_id: "heizung.temp_ww_wp"
        device_class: temperature
        unit_of_measurement: "°C"
      - name: "WP Betriebsstatus"
        value_template: "{{ (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 1314) | list | first).currentValue }}"      
        unique_id: "heizung.wp_betriebsstatus"
      - name: "Ist-Drehzahl Zuluftventilator"
        value_template: "{{ (value_json[0]['value'][0]['values'] | selectattr('parameterId','eq', 1184) | list | first).currentValue }}"
        unique_id: "heizung.zuluft_ist_drehzahl"
        unit_of_measurement: "1/min"
      - name: "Ist-Drehzahl Abluftventilator"
        value_template: "{{ (value_json[0]['value'][0]['values'] | selectattr('parameterId','eq', 1186) | list | first).currentValue }}"
        unique_id: "heizung.abluft_ist_drehzahl"
        unit_of_measurement: "1/min"
      - name: "Status WP"
        unique_id: "heizung.wp_betriebsstatus_label"
        value_template: >
            {% set mapper = {
              0 : 'Wiedereinschaltsperre',
              1 : 'Wärmepumpe aus',
              2 : 'Vorlaufzeit Solepumpe',
              3 : 'Vorlaufzeit Ventilatoren',
              4 : 'Öffnen Heissgasventil',
              5 : 'Öffnen Flüssiggasventil',
              6 : 'Start Kompressor',
              7 : 'Mindestlaufzeit Wärmepumpe',
              8 : 'Wärmepumpe ein',
              9 : 'Kältemittel absaugen',
              10 : 'Beim Abtauen absaugen',
              11 : 'Abtauen ein',
              12 : 'Nach Abtauen abtropfen',
              13 : 'Pufferentladung',
              14 : 'Abtaumodus definieren'} %}
            {% set state = (value_json[0]['value'][1]['values'] | selectattr('parameterId','eq', 1314) | list | first).currentValue %}
            {{ mapper[state] if state in mapper else 'Unbekannt' }}
    
            
        
    
